[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
name = "rustin"
edition = "2018"
version = "0.1.0"

[dependencies]
futures = "0.3.5"
regex = "1.3.9"

[dependencies.serde]
version = "1.0.114"
features = ["derive"]
